<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWbid9jt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWbid9jt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWbid9jt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWbid9jt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWbid9jt\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wbid9jt',
    'container.build_id' => '5071f6a0',
    'container.build_time' => 1743465617,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWbid9jt');
