<?php

namespace ContainerWbid9jt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_L_NtHd9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.L.NtHd9' shared service.
     *
     * @return \App\Repository\TacheRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\TacheController::updateTache()": the $repo argument is type-hinted with the non-existent class or interface: "App\\Repository\\TacheRepository".');
    }
}
