<?php

namespace ContainerWbid9jt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AH900CBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aH900CB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aH900CB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine', 'getDoctrineService', false],
            'repo' => ['privates', '.errored.VBKdkPF', NULL, 'Cannot determine controller argument for "App\\Controller\\TacheController::deleteTache()": the $repo argument is type-hinted with the non-existent class or interface: "App\\Repository\\TacheRepository".'],
        ], [
            'manager' => '?',
            'repo' => '?',
        ]);
    }
}
